### PR TITLE
Spelling mistake in REQUEST_CODE_UPPER_BOUND

### PR DESCRIPTION
**Pull request by mojadita**
Signed-off-by: Luis Colorado <lcu@basen.net>

### CODE REVIEW

**Comment by mojadita** [comment]
I think now everything is ok. :)

**Comment by sophokles73** [comment]
The `org.eclipse.californium.core.network.serialization.DataParser` class has a reference to `org.eclipse.californium.core.coap.CoAP.MessageFormat.REQUEST_CODE_UPPER_BOUNT` which needs to be refactored as well.
You should make sure that the code compiles successfully locally after you have made your changes. In particular, you should do a `mvn clean install` in order to make sure that you compile from scratch ...

**Comment by mojadita** [comment]
I did it, but it's clear that I did it bad.  Let me check all compilations.

**Comment by sophokles73** [comment]
Merged in 8b5de7d796fcf49357b7f24c98c86886a2fe6d27

Thanks for the fix, @mojadita :-)

**Pull request closed without merging**
