### PR TITLE
Spelling mistake in REQUEST_CODE_UPPER_BOUND

### PR DESCRIPTION
**Pull request by mojadita**
I have just got your source to compile locally, and got this spelling mistake in your CoAP class.

### CODE REVIEW

**Comment by sophokles73** [comment]
Hi @mojadita,

thanks for submitting the PR :-) It seems that you currently do not have a signed Eclipse CLA (at least not for the email address you used in the commit log) which is a pre-requisite for us to accept the PR. Signing the CLA is no big deal so I would like to encourage you to do so [as described on the Eclipse web site](https://www.eclipse.org/contribute/) and also include a "signed-off" footer in your commit message (using `git commit -s`) so that we can merge this and any future PRs of yours :-)

**Comment by mojadita** [comment]
Hi, I have registered as luiscoloradourcola@gmail.com into eclipse account
registry. I'll try to follow your steps, as probably I'll get in touch with
californium a lot in the near future.  I was involved in a CoAP
implementation before I was directed to your page by my colleagues at my
company.

The patch I submitted is not important, just a mispelled word.  After
correcting and compiling I detected no warnings in the code, so the
constant is not being used in the project at least.



*Luis Colorado Urcola*
*Hakarinne 2, N170*

*02100 EspooFI*
*Cellphone: +358 40 77 321 77*

2015-11-24 16:04 GMT+02:00 Kai Hudalla <notifications@github.com>:

**Comment by mojadita** [comment]
I have already signed the CLA with my email address, how to pass again the ip-validation test?

**Comment by sophokles73** [comment]
Hi @mojadita,

it seems that you have included a lot more than just the spelling mistake fix in your PR now. In particular it includes commits from other people as well that do not have a CLA or haven't signed off their commits.
I think the easiest way for you to get it right would be to create a clean new fork from master, clone it on your local machine, create a branch, make your fix and commit (don't forget the "signed-off" footer) and push it back to your fork. Then create the PR from that branch and it should work out fine ...

**Comment by mojadita** [comment]
Yes, you are right, I received a conflict on pulling and I tried to correct it (probably the wrong way).  I'll do as you suggest.  Sorry for the inconveniences.

**Comment by sophokles73** [comment]
No problem at all, I am more afraid that you consider all of this not worth the effort for supplying a fix to a typo. However, maybe you should just consider it a training session in GitHub ;-)

**Pull request closed without merging**
