### PR TITLE
Mistake in OptionNumberRegistry.isCritical

### PR DESCRIPTION
**Pull request by mojadita**
Signed-off-by: Luis Colorado lcu@basen.net

### CODE REVIEW

**Comment by mojadita** [comment]
I discovered this bug trying to integrate library on own code.  As of reviewing more, I discovered more errors in the OptionNumberRegistry so I wrote several Unit tests to check all the options against RFC-7252 doc.

**Comment by sophokles73** [comment]
Hi @mojadita,

thanks for your PR :-) We have merged californium.core, californium.scandium and californium.element-connector into the caifornium repo several weeks ago. Can you please re-open your PR against that repo (https://github.com/eclipse/californium)?

Thanks,
Kai

**Comment by mojadita** [comment]
Ok... Thanks... I'll do it.

**Comment by sbernard31** [comment]
Maybe we should change the master branch by just committing a README.md file to redirect to the right repository. Something like that ? https://github.com/jvermillard/leshan 
(if we want to keep the master just in case we can keep it in a `oldmaster` branch)

**Comment by mkovatsc** [comment]
+1 for oldmaster
(also +1 for the fix, but that will only matter in the new PR :) )

**Comment by sbernard31** [comment]
(ok I will do that for californium.core, californium.scandium and californium.element-connector)

**Comment by mkovatsc** [comment]
Okay, thanks! (There is already the "oldmaster" branch for californium.core ;) )

**Pull request closed without merging**
